eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10001
spring:
  application:
    name: api-gateway-zuul
zuul:
  routes:
    api-a:
      path: /rest-users/**
      serviceId: UserService-Provider
    api-b:
      path: /rest-songs/**
      serviceId: SongService-Provider