eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10001
spring:
  application:
    name: api-gateway-zuul
zuul:
  routes:
    rest-users:
      path: /rest-users/**
      serviceId: UserService-Provider
    rest-songs:
      path: /rest-songs/**
      serviceId: SongService-Provider
    rest-singer:
      path: /rest-singer/**
      serviceId: SingerService-Provider
    rest-album:
        path: /rest-album/**
        serviceId: AlbumService-Provider
    rest-usercomment:
        path: /rest-usercomment/**
        serviceId: UserCommentService-Provider
