server:
  port: 10000
spring:
  application:
    name: admin-ui
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    refresh:
      enabled: false
info:
  version: @project.version@
  turbine:
    clusters: default
    url: http://localhost:10002/turbine.stream