server:
  port: 10000
spring:
  security:
    user:
      name: "user"
      password: "password"
  application:
    name: tmcloud-admin-ui
  mail:
    host: smtp.163.com
    username: tanjian20150101@163.com
    password: jaredtan95
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          from: tanjian20150101@163.com
          to: jian.tan@daocloud.io #逗号分隔,773767470@qq.com
          ignore-changes: "UNKNOWN:OFFLINE"
          subject: "Spring Boot Admin通知: #{application.name} (#{application.id}) is #{to.status}."
          text: "hi~,your app #{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}\n\n you can learn more about it from #{application.healthUrl}."
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: turbine
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka.didispace.com}/eureka/
      #defaultZone: http://localhost:8761/eureka/
management:
  health:
    refresh:
      enabled: false
  security:
    enabled: false #暂时关闭Spring security，才能查看actuator 端点监控
