eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
      #利用【公益】开放一台Eureka注册中心给各位Spring Cloud爱好者
      #Dashboard ： http://eureka.didispace.com/
      #defaultZone: http://eureka.didispace.com/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 11111
spring:
  application:
      name: AuthService
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  mvc:
    throw-exception-if-no-handler-found: true #当出现 404 错误时, 直接抛出异常
  resources:
    add-mappings: false             #不要为我们工程中的资源文件建立映射
logging:
  level:
    root: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
